# Generated by Django 4.1.7 on 2023-03-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_board_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Adress',
            field=models.TextField(default=None, max_length=4000),
        ),
    ]
