# Generated by Django 4.1.7 on 2023-03-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_alter_post_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=None, upload_to='static/img'),
            preserve_default=False,
        ),
    ]
