# Generated by Django 4.1.7 on 2023-04-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_topic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='Adress',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='topic',
            name='message',
            field=models.TextField(default=' ', max_length=4000),
            preserve_default=False,
        ),
    ]
